Feature/#1
GDSC-KNU/TIL-Backend pull request #7
Opened 2022-04-28 13:41 UTC by JiwonHwang01

Signup & Login 기능 1차 구현

2022-04-28 14:24 UTC, gidskql6671 requested changes
약간 리뷰해봤어요.
추가로 혹시 정상적으로 동작하는지 테스트해보았나요? 저도 Security쪽은 잘 몰라서, 단순히 보는 걸로는 잘 동작하는지 알 수 없어서 여쭤봐요 :)

2022-04-28 14:24 UTC, gidskql6671 commented on server/src/main/java/gdsc/knu/til/model/network/request/UserApiRequest.java
> +public class UserApiRequest {
해당 클래스는 미사용하는 것 같네요. 사용하지 않는 경우 삭제해주시면 될 것 같아요.

그리고 혹시 model 폴더와 domain 폴더를 따로 두신 이유가 있을까요?

2022-04-28 14:32 UTC, JiwonHwang01 commented on server/src/main/java/gdsc/knu/til/controller/HomeController.java
> +}
네 불필요한 파일 제거할게요ㅎㅎ코드리뷰 감사합니다

2022-04-28 14:35 UTC, JiwonHwang01 commented on server/src/main/java/gdsc/knu/til/domain/User.java
> +    private String account;
오우 알려주셔서 감사해요,, 수정해볼게요!

2022-04-30 12:36 UTC, gidskql6671 commented on server/src/main/java/gdsc/knu/til/dto/UserSignupRequestDto.java
> +
해당 클래스는 UserSingupRequestDto이고, 클라이언트(어플)에서 서버에 회원가입 요청을 보낼 때 사용하는 데이터를 지칭하는 클래스네요?

사용하신 `@Id`와 `@GeneratedValue` 어노테이션은 데이터베이스와 연동되는 Entity 클래스의 필드에 붙이는 어노테이션이에요. 지원님이 작성하신 코드로는 model 패키지에 있는 User 클래스가 Entity 클래스에 해당되구요.
그러니 해당 어노테이션은 지워주셔야 해요.

그리고 어노테이션 말고 id 필드 자체로만 보면, 해당 클래스는 유저가 서버에 회원가입을 요청할 때 사용하는 클래스죠? 유저가 회원가입을 요청할 때는 자신의 계정(account)와 비밀번호(password) 정보 이외에 데이터베이스에 저장될 Primary Key를 넘겨줄 필요가 있을까요? 그건 유저의 책임이 아닐거에요. 

``` suggestion
```
그래서 해당 필드는 불필요해보여요 :)

2022-04-30 13:06 UTC, gidskql6671 requested changes

2022-05-02 11:38 UTC, JiwonHwang01 commented on server/src/main/java/gdsc/knu/til/dto/UserSignupRequestDto.java
> +
오,,,알려주셔서 감사해요. 바로 수정했어요!

2022-05-05 09:02 UTC, JiwonHwang01 commented on server/src/main/java/gdsc/knu/til/domain/User.java
> +    }
편하실 때 변경한 거 확인 부탁드려요 : )

2022-05-06 09:34 UTC, gidskql6671 commented on server/src/main/java/gdsc/knu/til/model/User.java
> +    private LocalDateTime createdAt;
생성 시간같은 경우는 코드로 직접 넣어주기보단 JPA Auddit 기능을 사용하여 추가해주는게 일반적이에요.

해당 [링크](https://hyerin6.github.io/2021-08-14/createdAt/) 참고해보시면 좋아요. 아주 간단하게 설명되어 있어서 적용하는데 어려움이 없을 거에요. 다만 너무 간단하게 설명된 감이 있어서 추가로 더 알아보시면 도움이 되실거에요.

2022-05-06 09:34 UTC, gidskql6671 commented on server/src/main/java/gdsc/knu/til/provider/JwtTokenProvider.java
> +    private String secretKey = "TilBeGDSC";
secretKey같은 중요한 데이터는 하드코딩하면 안돼요~
제가 database.properties 파일을 정의하고 .gitignore에 추가한 것처럼 퍼블릭한 공간에 올라오지 않도록 분리해주어야 해요. 우선은 database.properties 파일에 시크릿 키를 정의해주고, 그걸 사용하는 방식으로 변경해봐요~

2022-05-06 09:34 UTC, gidskql6671 commented on server/src/main/java/gdsc/knu/til/service/AuthService.java
> +@ResponseStatus(HttpStatus.SERVICE_UNAVAILABLE)
제가 알기론 `@ResponseStatus`는 컨트롤러나 Execption에 적용하여서 지정한 상태코드를 응답으로 보내주도록 하는 어노테이션으로 알고있는데, 혹시 서비스 계층에 부여하신 이유가 있을까요?

2022-05-06 09:34 UTC, gidskql6671 commented on server/src/main/java/gdsc/knu/til/service/AuthService.java
> +    }
Service 계층에서 `ResponseEntity`를 반환하도록 하는 것은 좋지 않은 구조에요. ResponseEntity는 응답으로 보내줄 데이터와 상태코드 등을 가지는 클래스로, 달리 말하면 HTTP 응답 데이터를 담는 클래스에요. 그런데 스프링의 계층 구조에서 서비스 계층은 이 HTTP 응답과 관련되는 계층이 아니에요. 서비스 계층은 특정한 비즈니스 로직을 구현하는 계층이고, 이 예시에서는 로그인과 회원가입이 되겠죠. 그렇다면 해당 함수들의 반환값은 HTTP 응답과 관련된 ResponseEntity가 아니라 로그인이라는 기능에 대한 반환값이 되어야 해요.

그래서 해당 함수들의 반환값은 해당 커밋 이전의 반환값이 더 적절해보여요. HTTP 응답에 대한 처리는 컨트롤러 계층에서 하시면 됩니다. 만약 회원가입 함수의 반환값이 null이라면, 정상적으로 만들지 못한 것이니 ResponseEntity를 통해 적절한 상태코드를 지정해주면 되겠죠

2022-05-06 09:36 UTC, gidskql6671 commented
위 리뷰랑 별개로 현재 회원가입과 로그인하면서 JWT 생성하는 것은 정상적으로 처리되는데, JWT를 사용하여 로그인 상태를 확인하고 그에 따라 접근을 허용/차단하는 부분은 구현이 되어있지 않네요.
해당 [링크]를 참조하시면 좋을 것 같아요. 인터셉터라는 개념이 현재 구현에는 빠져있는 것 같아요 :)

2022-05-11 10:57 UTC, JiwonHwang01 commented on server/src/main/java/gdsc/knu/til/model/User.java
> +@Setter
자세히 다시 설명해주셔서 이해했어요 :)

2022-05-16 10:44 UTC, JiwonHwang01 commented on server/src/main/java/gdsc/knu/til/model/User.java
> +@Data
수정했어요!

2022-05-27 20:22 UTC, JiwonHwang01 commented on server/src/main/java/gdsc/knu/til/service/AuthService.java
> +    }
동환님 이 부분 수정했는데 확인부탁드려요,,

2022-05-29 03:28 UTC, gidskql6671 commented on server/src/main/java/gdsc/knu/til/service/AuthService.java
> +    }
확인햇어요~ 몇가지 수정하고 머지할게용

2022-05-29 03:28 UTC, merged